### ISSUE TITLE
vmware7_connection_status : max_bytes_length_exceeded_exception

### ISSUE THREAD

**Issue by marcolefo** [dcecchino/glog#17]
**Describe the bug**
_vmware7_connection_status_  is in error : _max_bytes_length_exceeded_exception_

The erros are displayed in Indexer failures.

- Graylog 5.2.1
- Opensearch 2.11.0
- vcenter 8.0.2
- ESXi 7.0.3

**Complete error message**
`
OpenSearchException[OpenSearch exception [type=illegal_argument_exception, reason=Document contains at least one immense term in field="vmware7_connection_status" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[51, 92, 110, 50, 48, 50, 51, 45, 49, 48, 45, 48, 53, 84, 49, 52, 58, 48, 49, 58, 48, 57, 46, 48, 50, 53, 43, 48, 50, 58]...', original message: bytes can be at most 32766 in length; got 57926]]; nested: OpenSearchException[OpenSearch exception [type=max_bytes_length_exceeded_exception, reason=bytes can be at most 32766 in length; got 57926]];
`

**Extractor configuration**
Extractor type: Regular expression
Source field: message
Regular expression: `is (.*)]` 

Hi 
We have this error since we have installed Glog.
I'm new to Graylog and even more so with Glog. Perhaps it's normal but I prefer to keep you informed.

Thanks

**Comment by dcecchino** [comment]
Make sure you send your vcenter to another input other than the hypervisor input

**Comment by dcecchino** [comment]
You can delete this extractor. On Oct 5, 2023, at 8:54 AM, marcolefo ***@***.***> wrote:﻿
Describe the bug
vmware7_connection_status  is in error : max_bytes_length_exceeded_exception
The erros are displayed in Indexer failures.

Graylog  5.6.1
Opensearch 2.10.0 **

Complete error message
OpenSearchException[OpenSearch exception [type=illegal_argument_exception, reason=Document contains at least one immense term in field="vmware7_connection_status" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[51, 92, 110, 50, 48, 50, 51, 45, 49, 48, 45, 48, 53, 84, 49, 52, 58, 48, 49, 58, 48, 57, 46, 48, 50, 53, 43, 48, 50, 58]...', original message: bytes can be at most 32766 in length; got 57926]]; nested: OpenSearchException[OpenSearch exception [type=max_bytes_length_exceeded_exception, reason=bytes can be at most 32766 in length; got 57926]]; 
Extractor configuration
Extractor type: Regular expression
Source field: message
Regular expression: is (.*)]
Hi
We have this error since we have installed Glog.
I'm new to Graylog and even more so with Glog. Perhaps it's normal but I prefer to keep you informed.
Thanks

**Comment by marcolefo** [comment]
Ok thanks. I've done that
