### ISSUE TITLE
Error while trying to install 

### ISSUE THREAD

**Issue by ShajuDevassy** [dcecchino/glog#20]
Good day Dcechino,

I am a newbie here trying to get my Vcenter 7 logs into Graylog 6.1.4. 

While trying to install https://github.com/dcecchino/glog/blob/master/content_pack.json, i am getting : **Error Installing content pack failed with status: FetchError: There was an error fetching a resource: Internal Server Error. Additional information: Failed to install content pack <4522d51b-62da-4416-98d0-02a3193c6d45/2>. Could not install Content Pack with ID: 4522d51b-62da-4416-98d0-02a3193c6d45.**. Uploading the json file went fine

I have made a stream, index and my dedicated Syslog UDP Input of Vcenter is receiving data. 
The import of https://github.com/dcecchino/glog/blob/master/vmware7_extraction on the Input went fine too but seems it's not getting hits.

Need help with finding out where i am going wrong. Thanks very much.

**Comment by 0p4k** [comment]
Hi ShajuDevassy, I got the same issue and on logs "Caused by: org.graylog2.contentpacks.exceptions.ContentPackException: Stream with title <hypervisor> does not exist!" 
 Caused by: org.graylog2.contentpacks.exceptions.ContentPackException: Stream with title <Vmware Average Device Latency> does not exist!
 
 So I have created the both streams 
 hypervisor
 Vmware Average Device Latency
 I reinstall and it was good :)
